# Generated by Django 3.2.25 on 2025-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.TextField(max_length=20)),
                ('p_image', models.FileField(default=None, max_length=250, null=True, upload_to='all_product/')),
                ('p_keyword', models.TextField(max_length=255)),
                ('height', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('furniture_highlights', models.TextField(max_length=255)),
                ('wall_features', models.TextField(max_length=255)),
                ('room_highlights', models.TextField(max_length=255)),
                ('lighting', models.TextField(max_length=255)),
                ('storage_features', models.TextField(max_length=255)),
                ('unique_id', models.CharField(max_length=20)),
            ],
        ),
    ]
