# Generated by Django 3.2.25 on 2025-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_message',
            fields=[
                ('c_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.TextField(max_length=10)),
                ('c_email', models.EmailField(max_length=20)),
                ('c_message', models.TextField(max_length=100)),
            ],
        ),
    ]
