# Generated by Django 3.2.25 on 2025-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('designer_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.TextField(max_length=20)),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=100)),
                ('user_name', models.TextField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=True, unique=True)),
                ('mobile_no', models.CharField(max_length=12)),
                ('company_name', models.TextField(max_length=20)),
                ('company_address', models.TextField(max_length=100)),
                ('about_company', models.TextField(max_length=500)),
                ('website_link', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.TextField(max_length=20)),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=100)),
                ('user_name', models.TextField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=True, unique=True)),
                ('mobile_no', models.CharField(max_length=12)),
                ('company_name', models.TextField(max_length=20)),
                ('company_address', models.TextField(max_length=100)),
                ('about_company', models.TextField(max_length=500)),
                ('website_link', models.TextField(max_length=100)),
            ],
        ),
    ]
