# Generated by Django 5.1 on 2025-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='photo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='designer/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='user/'),
        ),
    ]
