# Generated by Django 3.2.25 on 2025-06-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.TextField(max_length=100)),
                ('blog_img', models.FileField(default=None, max_length=250, null=True, upload_to='blog/')),
                ('blog_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
